import React from 'react'
import Feature from './Feature'
import styles from "./styles.module.css"
import one from "../../assets/misc/1.svg"
import two from "../../assets/misc/2.svg"
import three from "../../assets/misc/3.svg"
type Props = {}

function Features({}: Props) {
  return (
      <div className={styles.container} >
          <Feature title="Search" description="Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen." image={one} />
          <Feature title="Select" description="Choose from thousands of options generated by the slogan maker that fit your needs." image={two} />
          <Feature title="Stand Out" description="Congrats on your new slogan. It's time to win the world!" image={three} />
      </div>
  )
}

export default Features
